# MODEL
channels: 3
filters: 16

# LOSS
mseWeight: 1
msSsimWeight: 1
vggWeight: 0

# DATASET
trainDatasetPath: '../dataset/Legni02@resize_16x_TRAIN'
cutSizeH: 128
cutSizeW: 256
maxShift: 15
minShift: 0
batchSize: 2
numWorkers: 4
shuffle: true

# TRAINING
lr: 0.0002
epochs: 100
logDir: '../logs/'
logStepFrequency: 250
modelsDir: '../models/'